### ISSUE TITLE
[Bug] Wrong timestamps and combat times

### ISSUE THREAD

**Issue by djdookie** [Xyaren/arcdps-log-uploader#21]
For some ArcDPS logs the timestamps and combat times are wrong if I choose detailed WvW logs.
Without detailed logs they are fine.
It looks like this only occurs for bigger files or longer fights.

With detailed WvW logs option (wrong):
`01.10.2022` `23:35` `00m 00s` <https://wvw.report/Vf5V-20221001-213513_wvw>
`01.10.2022` `23:43` `00m 00s` <https://wvw.report/qQ4U-20221001-214316_wvw>
`01.10.2022` `23:56` `00m 00s` <https://wvw.report/PaGg-20221001-215624_wvw>
`02.10.2022` `00:01` `00m 00s` <https://wvw.report/v5V0-20221001-220139_wvw>
`02.10.2022` `00:50` `00m 00s` <https://wvw.report/jQhp-20221001-225029_wvw>
`02.10.2022` `00:56` `00m 00s` <https://wvw.report/iome-20221001-225638_wvw>
(look at the combat times and compare the timestamps with the correct timestamps in the file name)

Without detailed WvW logs option (correct):
`21:31` `03m 45s` <https://wvw.report/1Cr8-20221001-213513_wvw>
`21:40` `02m 56s` <https://wvw.report/Gvyx-20221001-214316_wvw>
`21:53` `02m 56s` <https://wvw.report/URQR-20221001-215624_wvw>
`21:56` `04m 53s` <https://wvw.report/Aojd-20221001-220139_wvw>
`22:44` `06m 07s` <https://wvw.report/CFoy-20221001-225029_wvw>
`22:50` `06m 06s` <https://wvw.report/IO4A-20221001-225638_wvw>

All copied from the discord tab after uploading.
Most of the detailed logs are correct, but here I only picked some that are broken.
The wrong timestamps are all shifted 2 hours, so I guess this could be a timezone problem, since my PC is in the CEST (UTC+2) timezone.

I like this tool but this bug unfortunately makes it unusuable for me right now.

**Comment by Xyaren** [comment]
Thank you for the report. 
Can you attach me a one or two of the files for testing and debugging ?

**Comment by djdookie** [comment]
Sure. 
[20221001-225638.zip](https://github.com/Xyaren/arcdps-log-uploader/files/9760243/20221001-225638.zip)

**Comment by Xyaren** [comment]
Thank you. It looks like a problem from dps.report, I forwarded the issue and am currently awaiting a response.

**Comment by djdookie** [comment]
@Xyaren Thank you. Any updates on this?

**Comment by Xyaren** [comment]
Unfortunately not. 
I'm still waiting for a reply by the dps.report dev.

**Comment by Xyaren** [comment]
Closing due to no response from the Upstream arcdps.report site.
